TO BE COPIED TO E.G. /SDCARD/DOWNLOAD THEN INSTALLED MANUALLY VIA SETTINGS/SECURITY/ENCRYPTION&CREDENTIALS/INSTALL A CERTIFICATE/CA CERTIFICATE

INSTALLING VIA HONEYWELL ENTERPRISE PROVISIONER FAILS.

